# Generated by Django 2.1.7 on 2019-03-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
    ]
